name: Generate Gallery Index

on:
  push:
    branches:
      - main

jobs:
  generate-gallery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install fs path

      - name: Generate gallery index
        run: |
          node scripts/gen-gallery.js

      - name: Commit and push gallery-index.json
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add gallery-index.json
          git commit -m "🤖 Auto-update gallery index" || echo "No changes to commit"
          git push
